/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hu.bakondis.randomnumbergenerator.api;

import hu.bakondis.randomnumbergenerator.model.RandomNumber;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-07-12T08:26:44.398771931Z[GMT]")
@Validated
public interface GetRandomNumberApi {

    @Operation(summary = "Returns a random number", description = "Returns a random number", tags = {})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = RandomNumber.class))),

            @ApiResponse(responseCode = "400", description = "Invalid request"),

            @ApiResponse(responseCode = "405", description = "Validation exception")})
    @RequestMapping(value = "/getRandomNumber/{minNumber}/{maxNumber}",
                    produces = {"application/json"},
                    method = RequestMethod.GET)
    ResponseEntity<RandomNumber> getRandomNumber(@Parameter(in = ParameterIn.PATH, description = "the minimum number", required = true, schema = @Schema()) @PathVariable("minNumber") Long minNumber,
                                                 @Parameter(in = ParameterIn.PATH, description = "the maximum number", required = true, schema = @Schema()) @PathVariable("maxNumber") Long maxNumber);

}

